apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-deployment
  labels:
    app: golang-app
spec:
  selector:
    matchLabels:
      app: golang-app
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: golang-app
    spec:
      containers:
        - name: golang-app-container
          image: yuyatinnefeld/go-prometheus-app
          imagePullPolicy: Always
          ports:
            - name: golang-port
              containerPort: 8080
          resources:
            requests:
              memory: 0.5Gi
              cpu: "0.25"
            limits:
              memory: 1Gi
              cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: golang-app-svc
  labels:
    app: golang-app
spec:
  selector:
    app: golang-app
  ports:
    - name: http-port
      protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer