apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deploy
  labels:
    app: fastapi-app
spec:
  selector:
    matchLabels:
      app: fastapi-app
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
        - name: fastapi-app-container
          image: yuyatinnefeld/fastapi_prometheus:1.1.0
          imagePullPolicy: Always
          ports:
            - name: fastapi-port
              containerPort: 8080
          resources:
            requests:
              memory: 0.5Gi
              cpu: "0.25"
            limits:
              memory: 1Gi
              cpu: "0.5"

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-app-svc
  labels:
    app: fastapi-app
spec:
  selector:
    app: fastapi-app
  ports:
    - name: fastapi-port
      protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-app-servicemonitor
  # must by the same namespace that Prometheus is running in
  namespace: monitoring
  labels:
    app: fastapi-app
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: fastapi-app
  endpoints:
    - path: metrics
      port: fastapi-port
      interval: 15s
  namespaceSelector:
    any: true