version: '1'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  push_gateway:
    image: prom/pushgateway:v1.4.2
    ports:
      - 9091:9091