version: '1'
services:
  prometheus: #Prometheus Server
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  exporter: #Exporter VM
    image: prom/node-exporter
    container_name: exporter
    ports:
      - 9100:9100