import os

MONGO_HOST="mongodb" 
MONGO_DB_NAME="account_user"
MONGO_PORT=27017

MONGO_DB_USERNAME="root"    # FIX VALUE CANNOT CHANGE
MONGO_DB_PASSWOR="pass"     # FIX VALUE CANNOT CHANGE

ENVIRONMENT_DEBUG = os.environ.get("APP_DEBUG", True)
ENVIRONMENT_PORT = os.environ.get("APP_PORT", 5000)