apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-app-servicemonitor
  # must by the same namespace that Prometheus is running in
  namespace: prometheus
  labels:
    app: node-app
    release: prometheus
spec:
  selector:
    matchLabels:
      app: node-app
  endpoints:
    - path: swagger-stats/metrics
      port: node-port
      interval: 15s
  namespaceSelector:
    any: true