apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app-container
          image: yuyatinnefeld/node-web-app
          imagePullPolicy: Always
          ports:
            - name: node-port
              containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-svc
  labels:
    job: node-api
    app: node-app
spec:
  selector:
    app: node-app
  ports:
    - name: node-port
      protocol: "TCP"
      port: 5000
      targetPort: 5000
  type: LoadBalancer