apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webapps-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: my-storage-class