version: "3"
services:
  jupyter:
    image: jupyter/datascience-notebook:python-3.9.7
    container_name: jupyter
    ports:
      - 8888:8888
    volumes:
      - jupyter-data:/home/jovyan
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    command: "start-notebook.sh --NotebookApp.token='yuya' --NotebookApp.password='password'"

volumes:
  jupyter-data:
    driver: local

