version: "3"
services:
  jupyter:
    image: jupyter/datascience-notebook:python-3.9.7
    container_name: jupyter
    ports:
      - 8888:8888
    volumes:
      - jupyter-data:/home/jovyan/work

volumes:
  jupyter-data:
    driver: local

