apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-relicaset
  labels: 
    type: front-end
    app: myapp
spec:
  template:
    metadata:
      name: myapp-pod
      labels: 
        type: front-end
        app: myapp
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 4
  selector:
    matchLabels:
      type: front-end


