apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-app-servicemonitor
  # must by the same namespace that Prometheus is running in
  namespace: prometheus
  labels:
    app: fastapi-app
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: fastapi-app
  endpoints:
    - path: metrics
      port: fastapi-port
      interval: 15s
  namespaceSelector:
    any: true