apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-staging
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: staging
    server: https://kubernetes.default.svc
  project: default
  source:
    path: wordpress/overlays/staging
    repoURL: https://gitlab.com/cloudnativetips/cd-sample.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - validate=true
      - CreateNamespace=true
      - PruneLast=false
      - Replace=false
      - ApplyOutOfSyncOnly=false
      - PrunePropagationPlocy=foreground
